### ISSUE TITLE
Undefined symbols error when trying to build iOS

### ISSUE THREAD

**Issue by Liamandrew** [orel91/react-native-launch-darkly#4]
I'm trying to integrate this package however when I build iOS I receive the following error from xcode:
```
Undefined symbols for architecture x86_64:
  "_kLDFlagConfigChangedNotification", referenced from:
      -[RNLaunchDarkly configure:options:] in libRNLaunchDarkly.a(RNLaunchDarkly.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've tried linking automatically and manually, however I receive the same error via both methods. The issue seems to be due to fact that the constant **kLDFlagConfigChangedNotification** is undefined.

Is this something you've experienced before? Or do you have any idea on a solution?

Cheers.

**Comment by jwilliamson-qb** [comment]
Same is happening with me. ☝️
